// database.js - Banco de dados compartilhado entre app.js e admin.html
// Este arquivo define os produtos padrão das bibliotecas D.A.W.LOAD

const defaultProducts = [
  // Bibliotecas Pagas
  {
    id: "vst-stage",
    title: "VST Stage",
    category: "pagas",
    tagLabel: "Premium",
    desc: "Interface de alta performance ao vivo com splits, layers e presets prontos para palcos e igrejas.",
    rating: 5.0,
    ratingCount: 142,
    oldPrice: 249.99,
    price: 219.99,
    discount: "12% OFF",
    meta: ["Versão 2.1", "Kontakt Full", "Win/macOS"],
    image: "assets/vst_stage.png",
    searchTags: "vst stage teclado stage live performance worship layers splits presets premium",
    youtube: "https://www.youtube.com/watch?v=h-13A0Ltv1E",
    midi: "https://siloedavid.com/demo/vst-stage/",
    downloadLink: ""
  },
  {
    id: "abba-keys",
    title: "aBBa Keys",
    category: "pagas",
    tagLabel: "Premium",
    desc: "Teclados retrô inspirados no som do ABBA. Synths vintage clássicos dos anos 70 e 80 com muita presença.",
    rating: 4.8,
    ratingCount: 65,
    oldPrice: 219.99,
    price: 199.99,
    discount: "9% OFF",
    meta: ["Versão 1.1", "Retro Synths", "Kontakt Full"],
    image: "assets/abba_keys.png",
    searchTags: "abba keys teclado keys synth retro anos 70 80 pop keys vintage classico",
    youtube: "https://www.youtube.com/watch?v=h-13A0Ltv1E",
    midi: "",
    downloadLink: ""
  },
  {
    id: "piano-stage",
    title: "Piano Stage 4",
    category: "pagas",
    tagLabel: "Premium",
    desc: "Piano elétrico de palco CP80 brilhante e cortante que se destaca perfeitamente em arranjos de banda ao vivo.",
    rating: 4.8,
    ratingCount: 52,
    oldPrice: 189.99,
    price: 149.99,
    discount: "21% OFF",
    meta: ["Versão 1.0", "CP80 Electric", "Kontakt Full"],
    image: "assets/piano_stage.png",
    searchTags: "piano stage stage pianos teclado live cp80 piano stage eletrico vintage live performance",
    youtube: "https://www.youtube.com/watch?v=h-13A0Ltv1E",
    midi: "",
    downloadLink: ""
  },
  {
    id: "infinity-pads",
    title: "Infinity Pads",
    category: "pagas",
    tagLabel: "Premium",
    desc: "Pads e texturas atmosféricas profundas e evolutivas. Ideal para bases, worship, ambientações e trilhas.",
    rating: 5.0,
    ratingCount: 118,
    oldPrice: 149.99,
    price: 89.99,
    discount: "40% OFF",
    meta: ["Versão 1.2", "Pads & Atmosferas", "Kontakt Full"],
    image: "assets/infinity_pads.png",
    searchTags: "infinity pads pad synth atmosfera pads pads worship worship infinity",
    youtube: "https://www.youtube.com/watch?v=0gv7W1UDt7o",
    midi: "https://siloedavid.com/demo/infinity-pads/",
    downloadLink: ""
  },
  {
    id: "infinity-mix",
    title: "Infinity Mix",
    category: "pagas",
    tagLabel: "Premium",
    desc: "Ferramenta de mixagem rápida com compressores e equalizadores integrados para lapidar canais no Kontakt.",
    rating: 4.9,
    ratingCount: 41,
    oldPrice: 149.99,
    price: 89.99,
    discount: "40% OFF",
    meta: ["Versão 1.0", "Mix Tool / EQ & Comp", "Kontakt Full"],
    image: "assets/infinity_mix.png",
    searchTags: "mix mixagem mixer plugin compressao equalizacao infinity mix efeitos",
    youtube: "https://www.youtube.com/watch?v=h-13A0Ltv1E",
    midi: "https://siloedavid.com/demo/infinity-mix/",
    downloadLink: ""
  },
  {
    id: "intimate",
    title: "Intimate",
    category: "pagas",
    tagLabel: "Premium",
    desc: "Fusão acústica expressiva de felt piano e cordas em uma sonoridade íntima, suave e delicada.",
    rating: 5.0,
    ratingCount: 74,
    oldPrice: 99.99,
    price: 49.99,
    discount: "50% OFF",
    meta: ["Versão 1.0", "Felt Piano & Strings", "Kontakt Full"],
    image: "assets/intimate.png",
    searchTags: "intimate strings cordas felt piano suave felt piano intimate",
    youtube: "https://www.youtube.com/watch?v=0gv7W1UDt7o",
    midi: "",
    downloadLink: ""
  },

  // Bibliotecas Grátis
  {
    id: "dawload-keys",
    title: "Daw Keys Free",
    category: "gratis",
    tagLabel: "Grátis",
    desc: "Teclados e sintetizadores digitais com timbres essenciais para produção e arranjos rápidos no seu setup.",
    rating: 4.7,
    ratingCount: 38,
    oldPrice: null,
    price: 0.00,
    discount: null,
    meta: ["Versão 1.0", "Digital Keys", "Kontakt Free/Full"],
    image: "assets/dawload_keys.png",
    searchTags: "dawload keys d.a.wload keys teclado synth gratis timbres basicos",
    youtube: "https://www.youtube.com/watch?v=h-13A0Ltv1E",
    midi: "",
    downloadLink: ""
  },
  {
    id: "grand-stage",
    title: "Grand Stage",
    category: "gratis",
    tagLabel: "Grátis",
    desc: "Piano de cauda de concerto acústico amostrado com excelente sonoridade e ótima resposta dinâmica.",
    rating: 4.9,
    ratingCount: 154,
    oldPrice: null,
    price: 0.00,
    discount: null,
    meta: ["Versão 1.5", "Concert Grand Piano", "Kontakt Free/Full"],
    image: "assets/grand_stage.png",
    searchTags: "grand stage piano de cauda concerto gratis piano acustico",
    youtube: "https://www.youtube.com/watch?v=0gv7W1UDt7o",
    midi: "",
    downloadLink: ""
  },
  {
    id: "worship-stage-1",
    title: "Worship Stage 1",
    category: "gratis",
    tagLabel: "Grátis",
    desc: "Timbres essenciais de piano acústico e pads quentes ideais para base de louvor e adoração.",
    rating: 4.8,
    ratingCount: 92,
    oldPrice: null,
    price: 0.00,
    discount: null,
    meta: ["Versão 1.0", "Pianos & Pads", "Kontakt Free/Full"],
    image: "assets/worship_stage_1.png",
    searchTags: "worship stage 1 um piano pads ambientacao worship base gratis",
    youtube: "https://www.youtube.com/watch?v=h-13A0Ltv1E",
    midi: "",
    downloadLink: ""
  },
  {
    id: "worship-stage-2",
    title: "Worship Stage 2",
    category: "gratis",
    tagLabel: "Grátis",
    desc: "Camadas profundas de sintetizadores e pads brilhantes em textura digital ideal para ambientações mais complexas.",
    rating: 4.9,
    ratingCount: 87,
    oldPrice: null,
    price: 0.00,
    discount: null,
    meta: ["Versão 1.0", "Ambient Textures", "Kontakt Free/Full"],
    image: "assets/worship_stage_2.png",
    searchTags: "worship stage 2 dois synths texturas ambientacao gratis",
    youtube: "https://www.youtube.com/watch?v=0gv7W1UDt7o",
    midi: "",
    downloadLink: ""
  }
];

const defaultCombos = [
  {
    id: "combo-duo",
    tag: "Mais Vendido",
    isPopular: false,
    title: "Combo Duo Stage & Keys",
    subtitle: "VST Stage + aBBa Keys",
    oldPrice: 419.98,
    price: 335.98,
    discountBadge: "+20% OFF EXTRA",
    features: [
      "VST Stage (Presença ao vivo e splits)",
      "aBBa Keys (Synths retrô dos anos 70/80)",
      "Acesso vitalício aos downloads",
      "Suporte VIP com desenvolvedores"
    ],
    products: "vst-stage,abba-keys"
  },
  {
    id: "combo-trio",
    tag: "Destaque Worship",
    isPopular: true,
    title: "Combo Trio Pianos & Pads",
    subtitle: "Pianos Stage + Infinity Pads + Infinity Mix",
    oldPrice: 329.97,
    price: 263.98,
    discountBadge: "+20% OFF EXTRA",
    features: [
      "Pianos Stage (Piano elétrico CP80 cortante)",
      "Infinity Pads (Pads & atmosferas evolutivas)",
      "Infinity Mix (Equalizador e compressor fácil)",
      "Suporte VIP com desenvolvedores"
    ],
    products: "piano-stage,infinity-pads,infinity-mix"
  },
  {
    id: "combo-pack",
    tag: "Super Pack",
    isPopular: false,
    title: "Pack Completo (6 Bibliotecas)",
    subtitle: "Todas as Bibliotecas Pagas D.A.W.LOAD",
    oldPrice: 799.94,
    price: 639.95,
    discountBadge: "+20% OFF EXTRA",
    features: [
      "VST Stage, aBBa Keys, Pianos Stage",
      "Infinity Pads, Infinity Mix, Intimate",
      "Atualizações gratuitas futuras",
      "Atendimento direto com Rafael e Alex"
    ],
    products: "all-paid"
  },
  {
    id: "combo-vip",
    tag: "Suporte VIP",
    isPopular: false,
    title: "Instalação Garantida",
    subtitle: "1 Biblioteca à escolha + Suporte de Instalação",
    oldPrice: 299.99,
    price: 249.90,
    discountBadge: "+20% OFF EXTRA",
    features: [
      "Escolha 1 biblioteca paga do site",
      "Acesso remoto por AnyDesk/TeamViewer",
      "Instalação completa e configuração",
      "Atendimento VIP direto via WhatsApp"
    ],
    products: "lib-suporte"
  }
];
